### ISSUE TITLE
curl example using tags and type

### ISSUE THREAD

**Issue by dpeart** [caronc/apprise-api#1]
Could you provide an example of how to use curl to send a notification including type and tags?

I can get it to work with the body and title:

> curl -d '{"body":"body test", "title":"title test"}' -H "Content-Type: application/json" http://localhost:8000/notify/abc123/

however, if I try to add the tag or type it errors.  Tag and type do work in the default cfg form.

thanks,
david

**Comment by caronc** [comment]
Hi,

You just need to add reference to the _tag_ itself.
![Tag Reference](https://user-images.githubusercontent.com/850374/71449819-e6ef4300-2723-11ea-85d4-2ae99996588e.png)

So with respect to your example:
```bash
# add "tag" reference:
curl -d '{"body":"body test", "title":"title test","tag":"mytag"}' \
    -H "Content-Type: application/json" \
   http://localhost:8000/notify/abc123/
```

Good luck!

**Comment by dpeart** [comment]
That is what I though it just doesn't send the notfication.  The server returns notification sent, but it never actually sends the message.  If I then remove just the tag it sends.

It will send fine from the localhost:8000/cfg/abc123 page setting the tag in the GUI.  Which is what I find odd.

david

**Comment by caronc** [comment]
I just double checked and it seems to work fine for me.
Things to note:

- the tag's are very case sensitive.
- You'll also want to make sure you got the `{KEY}` in the URL correctly (matching up with the one you defined in your config - `http://127.0.0.1:8000/cfg/abc123#config`)
- make sure you've defined the tag correctly in your configuration file. For a text config file, it will be like:
   ```
   # The tag is abc123 with respect to the below  example
   abc123=mailtos://bill.gates:mysecret@gmail.com/
   ```
- Another thing you could try is using the tag `all` which is reserved and will trigger all of your config (regardless of what tag you defined). Test that out and see if it works for you.

Let me know how it goes

**Comment by dpeart** [comment]
Not sure what I'm doing differently, but it is indeed now working.

How does the message Type play into the notification?

Thanks so much

**Comment by caronc** [comment]
You should be able to just adjust the curl request a wee bit more and include the `type` like so:
```bash
# add "type" reference:
curl -d '{"body":"body test", "title":"title test","tag":"mytag", "type:"success"}' \
    -H "Content-Type: application/json" \
   http://localhost:8000/notify/abc123/
```

Valid options are:
1. **info**  (_this is the default if you don't otherwise specify a type_)
1. **success**
1. **warning**
1. **error**

Let me know if you have any troubles.

**Comment by dpeart** [comment]
I can get this to send, but don't see anything in the message.  Doesn't matter if I send from the web form or curl.  I was curious as to what this is supposed to do for the message.  How should I see the type.

thanks
david

**Comment by caronc** [comment]
Hi,

So the thing with Apprise (as you know) is that it supports A LOT of services.  All of them have a message _body_, some have a _title_, even fewer can support icons/colors (driven by the _type_ field).

So depending on what service you're actually using, you may not get the benefit of the type field. Email for example doesn't use it.  Email is just text (title goes to subject, and body goes to the email body itself); it doesn't use the type.  If you're sending a SMS (Text Message), well then you're only utilizing the _body_ (nothing else). However, things like Telegram and/or Slack, MSTeams, etc are a very feature rich chatting service and Apprise uses the _type_ to change the icon and enhance the message.

So that's kind of the long answer.  The short answer is: if you're not seeing the benefit of the '_type_' field, it's probably just because you're configured with a service that doesn't leverage it (at least not yet anyway if it's possible to do so). :slightly_smiling_face: 

Hopefully that makes sense! Let me know if you still have any questions.

**Comment by dpeart** [comment]
Makes total sense.

I hope to get apprise integrated with my Hubitat Elevation home automation server.  At least that is my goal so I can send notification from Hubitat to whatever I chose via apprise.

david

**Comment by caronc** [comment]
Hi, did you have any more questions? If not, are you okay if I close this ticket off?

**Comment by dpeart** [comment]
Is there a GET command that will return the configuration information in JSON format?  Today I just get a string back and it is a POST command to IP:8000/cfg/abc123

Yes, you can close the ticket.

Thanks for all your help,
david

**Comment by caronc** [comment]
The GET request to the  `/cfg/` API end point will return the configuration _as is_ in a format that Apprise can parse and directly use.

The header `Content-Type` (defined in the same response) plays a big role in identifying the data returned. `text/yaml` is returned if it's in a YAML format and `text/plain` if it's in a text format.  Apprise can directly interpret/ingest this response type.  Hence, you can use the tool like so:
```bash
# With respect to your example:
apprise --config=http://IP:8000/cfg/abc123 -b "Hello World!" --tag=all

# The above would have read your configuration and notified all of your
# defined services
```

Can you explain what the _use case_ would be if a JSON response was returned?

**Comment by dpeart** [comment]
In Hubitat I would like to get the valid tags for a given configuration.  I can then use those tags in the nonfictions app to send information about what happens; a door opened, the lock is unlocked, washer is done, etc.

Today I do a POST to url:/get/label<url://get/label> and it returns a text version of the configuration as I see on the apprise web page.

It would just be easier to have a JSON format for the tag and tag value:

Tag: DavidEmail, Value: mailto://email.passwd@gmail.com

Actually I don’t even need the value, just the valid tags.  Is it possible to just get the tags back?

I then use the tags to send the notifications with a POST to url:/notify/label<url://notify/label> with the tag defined as we discussed before.

In Groovy (what Hubitat uses) it looks like:

try {
    def postParams = [
      uri: "${AppriseUrl}/notify/${label}",
                    requestContentType: 'application/json',
                    contentType: 'application/json',
                    body : ["body": emlText, "title":"${emlSubject}", "tag":"${service}"]
    ]
//                            log.info postParams

    asynchttpPost('myCallbackMethod', postParams, [dataitem1: "datavalue1"])

    } catch(Exception e) {
      log.error e.message
    }
}


    def myCallbackMethod(response, data) {
      log.debug "Apprise returned data: ${response.data}"
      log.debug "status of post call is: ${response.status}"
    }

I was just trying to get the tag information so you can see it within Hubitat when setting up the notification service.

Thanks,
david

**Comment by caronc** [comment]
Have a look at the attached PR I just created and let me know if that would be satisfactory (I provided examples as to how the new call would work)

**Comment by dpeart** [comment]
It looks good.

I tried to pull it and run it via docker-compose, but it isn't working.  I did see the new files, but when I issue a GET I get:
  The requested resource was not found on this server.

The command I tested with is:
curl -X GET -H "Content-Type: application/json" http://localhost:8000/json/urls/2

thanks,
david

**Comment by caronc** [comment]
you need to use [this branch](https://github.com/caronc/apprise-api/tree/tags-api-query).  Here is quick [download link](https://github.com/caronc/apprise-api/archive/tags-api-query.zip), otherwise:
```bash

git clone git@github.com:caronc/apprise-api.git
cd apprise-api
git checkout tags-api-query
```

**Comment by dpeart** [comment]
Using the zip and creating a new area worked.  I was hoping to just update my current version so I wouldn’t lose my database.  I couldn’t get that to work so I just recreated it.

I can now use the GET command and parse the incoming JSON data perfectly.


Thanks
david

**Comment by caronc** [comment]
Okay, well if you're happy with that then i'll merge it into the master branch.

Your configuration will only get lost if you don't mount the `/config` volume externally (otherwise you'll loose all of your persistent data each time you load a new container).  When the merge is complete, this ticket will automatically close, but don't be discouraged to ask any more questions if you have any. :slightly_smiling_face:

**Comment by dpeart** [comment]
Thanks a lot for your support.

I really like how easy it is to get notifications managed, and I can keep all my data out of the cloud.

david

**Comment by dpeart** [comment]
One more request.

Could you  put the apprise-api on hub.docker like you have apprise?

Thanks
david

**Comment by caronc** [comment]
This is the case already, now that the content got merged to the master branch, dockerhub automatically builds a new image. You may just need to pull it down from your side.

**Comment by dpeart** [comment]
This is the only apprise-api on hub.docker.com I can find.

https://hub.docker.com/r/plaguedr/apprise-api

Is that correct?

david

**Comment by caronc** [comment]
No,

Use my hosting of it [here](https://hub.docker.com/r/caronc/apprise)

**Comment by dpeart** [comment]
Yep, that worked.

I guess I could see that in the dockerfile.

Thanks
david
