### ISSUE TITLE
Binding to another port?

### ISSUE THREAD

**Issue by mattpackwood** [caronc/apprise-api#10]
is there a way to bind to another port (I have 8000 committed to a different application)?

**Comment by caronc** [comment]
Maybe this might work for you?
```bash
# Bind the internal port 8000 in the container to 9000 on your local machine
docker run --name apprise \
   -p 9000:8000 \
   -v /var/lib/apprise/config:/config \
   -d caronc/apprise:latest
```

Or are you installing the repository locally onto your machine and not using Docker at all?

**Comment by mattpackwood** [comment]
I am running it in Docker, testing it now, many thanks.  By the way, I look at the services you already support and the list is stunning!

**Comment by caronc** [comment]
Thank you for your praise.  If you can think of any notification services I don't support that you'd like to see, I'm always up for the challenge of trying to add it! :slightly_smiling_face:  With respect to _this_ ticket: by all means let me know if what I suggested doesn't work. Good luck!

Chris

Chris

**Comment by mattpackwood** [comment]
It seems to be running but I am getting the following, let me dig into this later today.
pi@raspberrypi-greengrass:~ $ curl -X POST -d '{"urls": "mailto://user:mattpackwood@gmail.com", "body":"test message"}' -H "Content-Type: application/json" http://localhost:9000/notify
curl: (7) Failed to connect to localhost port 9000: Connection refused

**Comment by caronc** [comment]
Hi @mattpackwood that's strange because that's really all there is to it.

Is it possible there is a (software) firewall enabled on your Raspberry pi device that has port 9000 closed from the computer you're accessing it on?

If you actually ssh to the Raspberry pi, can you see if the port is listening at least correctly?
```
# See if you're set to LISTEN on port 9000
netstat -nat | egrep 9000
```

**Comment by mattpackwood** [comment]
I have a docker-compose error I missed. I am going to have a go at rebuilding that from source and see where I end up.

**Comment by caronc** [comment]
Okay :) good luck! I'll leave this ticket open all the same. Let me know how it all goes!

**Comment by mattpackwood** [comment]
All sorted, I was having issues with docker-compose (I had to remove and re-install it).
