### ISSUE TITLE
How do I attach images to Discord notifications?

### ISSUE THREAD

**Issue by namelivia** [caronc/apprise-api#100]
I've read through the documentation and afaik Discord should handle notifications, I've tried doing the following post request to my apprise microservice:

```
curl -X POST http://172.18.0.10:8000/notify/testing -H "Content-Type: application/json" -d '{"attach": ["https://cdn.pixabay.com/photo/2016/03/21/23/25/link-1271843__480.png", "https://cdn.pixabay.com/photo/2016/03/21/23/25/link-1271843__480.png", "https://cdn.pixabay.com/photo/2016/03/21/23/25/link-1271843__480.png"], "body": "test"}'
```

But on discord it only appears the "test" string. Am I misusing the attachment feature or is it that is not supported by Discord?
Thank you very much!

**Comment by caronc** [comment]
This has been added in the last release. Closing ticket

**Comment by RaminMT** [comment]
Hi
Does this syntax also supported to send attachments to telegram?
