### ISSUE TITLE
Is there a timeout for calls to `notify()`?

### ISSUE THREAD

**Issue by dstathis** [caronc/apprise-api#112]
:question: **Question**
Is there any timeout for the `notify()` method. I want to make sure I don't leave code hanging forever if someone's email server is down. I've looked through the docs and can't seem to find any information.

**Comment by caronc** [comment]
i'm slow responding here, but there is `async_notify()` which you can leverage the timers built right into `asyncio`

**Comment by caronc** [comment]
Closing issue having not heard back.
