### ISSUE TITLE
docker hub 1.2.0

### ISSUE THREAD

**Issue by ioull** [caronc/apprise-api#115]
:question: **Question**

Hello,

Thanks for the good job ! 
Is it possible to remove the v1.2.0 tag on dockerhub ? 
It make some misunderstanding for which vesrion is up to date.
![image](https://user-images.githubusercontent.com/6410144/233040389-fb9b405f-a8a4-4635-a150-4bdfb0328312.png)

**Comment by caronc** [comment]
The version associated with the API is not aligned with the Apprise tool itself. So everything should be fine as is. Are you experiencing an issue?

**Comment by ioull** [comment]
If i well understand, 1.2.0 is an apprise version and 0.9.0 is an apprise-api version (which use apprise 1.3.0).
Docker is an apprise-api image. 
So If i understand well, 1.2.0 as no reason to be published on docker hub ? 

My issue was to use the label 1.2.0 thinking it was the last version, but the last version is the 0.9.0 (based on 1.3.0),

**Comment by caronc** [comment]
I fixed this and forgot to close off this ticket.  I apologize for the confusion before. the `v1.2.0` branch is gone now.
