### ISSUE TITLE
Non-latin symbols processing

### ISSUE THREAD

**Issue by squromiv** [caronc/apprise-api#122]
:beetle: **Describe the bug**
When I try to send a notification with non-latin symbols, it results to non-readable characters in received messages. Checked with Telegram and Gotify services.

:bulb: **Screenshots and Logs**
Test commands
`curl.exe -X POST -d "title=Title&body=Body - ԱՅՈՑ ԱՅԲՈՒԲԵՆ" http://server/notify/telegram`
Result
![image](https://github.com/caronc/apprise-api/assets/15985877/016ab63f-5388-4758-8669-1307eaef2180)

`curl.exe -X POST -d "title=Title&body=Body - аулцшльфз зщтцгч" http://server/notify/gotify`
Result
![image](https://github.com/caronc/apprise-api/assets/15985877/902bcbce-a710-4827-9c55-15926bac7c0d)

:computer: **Your System Details:**
 - OS: Ubuntu 22.04
 - the last verison Docker image of apprise-api

**Comment by caronc** [comment]
I'm not able to reproduce this, but i'm wondering if it's a Windows problem as i notice you're using `curl.exe`.

I'm using Fedora 38 myself,, and i checked out the `apprise-api` and then:
```bash
# in one window
docker-compose up

# i went to http://localhost:8000 and set up the telegram url

# Then in another terminal window:
curl -X POST -d "title=Title&body=Body - ԱՅՈՑ ԱՅԲՈՒԲԵՆ" http://localhost:8000/notify/apprise/?tag=all
# 2023-07-06 20:07:19,742 [INFO] apprise: Loaded 1 entries from memory://
# 2023-07-06 20:07:20,461 [INFO] apprise: Sent Telegram notification.
```

...and it worked perfectly:
![image](https://github.com/caronc/apprise-api/assets/850374/5cdd12ad-0221-495b-b043-cf4ae12d783a)

I also tried just sending it through the website as another means of testing it out:
![image](https://github.com/caronc/apprise-api/assets/850374/f79a4fd7-9a92-4a96-a2e8-5cfe3823d971)

... and it worked fine again.

Can you give me more details on your windows environment?  What is the language set up for it?  I think the `curl.exe` is mangling your data/payload and Apprise is just passing it along (garbage in, garbage out).

**Comment by caronc** [comment]
Can you provide me with more details on your `curl` call?  I think you can add `-v` and get a more verbose output so we can see what the `POST` actually looks like.

I'm hoping that your server passes along the text encoding in the payload (as it doesn't appear to be `utf-8` in your case.

**Comment by caronc** [comment]
Any further update to this?

**Comment by squromiv** [comment]
I am sorry. Was on vacation and had no access to internet. Will check in the nearest time. Thanks a lot for support.

**Comment by squromiv** [comment]
> I'm not able to reproduce this, but i'm wondering if it's a Windows problem as i notice you're using `curl.exe`.
I was wrong not to mention in the first message, that I had tried curl from Windows.

So today I have started curl from Ubuntu instance, where Aprise is located, and the result is good. All symbols are readable. It looks that something is wrong with Windows version of CURL app. Let`s close the issue.

**Comment by squromiv** [comment]
I have to go back to this problem, because still have no solution. I`ve found out, that command construction like this, using Unicode escape sequence representation, leads to the proper result for symbols mentioned above.

![2_in](https://github.com/caronc/apprise-api/assets/15985877/5184af1c-618d-455a-8e2c-3edd1c22d9fc)

![2_out](https://github.com/caronc/apprise-api/assets/15985877/8d33861d-02c8-412d-b950-2ff002a6c298)

But how to apply such a command, without manually typing escape sequence representation for every symbol?

**Comment by caronc** [comment]
What language is your OS in? I'm wondering if this falls when the default encoding isn't utf-8

**Comment by squromiv** [comment]
English.

**Comment by squromiv** [comment]
Finally, developers of curl confirmed, that the program has **limited/incomplete Unicode support on Windows**. Thanks for quick support.
