### ISSUE TITLE
How to secure requests to a public Apprise instance

### ISSUE THREAD

**Issue by kingp0dd** [caronc/apprise-api#126]
:question: **Question**
I don't know if there's already a way for this:
* my apprise instance will be publicly accessible
* planning to add token authentication so not everyone can just use it
* found out about Persistent Storage solution which lets you add a KEY/TOKEN to the request
* however, my matrix URL are dynamic (the room id changes)

End goal is:

`curl -XPOST -H "Content-type: application/json" -d '{ "urls" : "matrixs://user:pass@test.com/!V12312Eblxy:localhost" , "body" : "test"  }' 'http://192.168.0.179:8000/notify/TOKENHERE'`

But it seems that the URL saved in the Persistent Config file cannot be overridden. 

Is there another way to make `notify` requests secure?

**Comment by caronc** [comment]
Did you end up getting this working; would you be okay if i close the ticket?

**Comment by kingp0dd** [comment]
Oh yes i did! Thanks again
