### ISSUE TITLE
Add a configuration option for attachment limit

### ISSUE THREAD

**Issue by dnbz** [caronc/apprise-api#130]
:bulb: **The Idea**
Currently, the file upload limit is 5MB. Telegram, for instance, allows for a 50MB limit, and I'd like to upload larger files there. Perhaps I've missed something, but I haven't seen this as a configurable option anywhere

**Comment by caronc** [comment]
I think I resolved this one for you; going to push to the master for your review.

**Comment by dnbz** [comment]
Thanks! Installed from master today and larger file uploads work as expected now
