### ISSUE TITLE
Notifications from CLI failing

### ISSUE THREAD

**Issue by bkonicek** [caronc/apprise-api#14]
:question: **Question**

I've spun up an apprise-cli instance in Docker, and created a test configuration. It successfully sends from the API frontend UI. When I exec into the container and try to send a notification using the apprise CLI it's failing with the error in the screenshot (note that the port number is different from the UI since I'm attached to the container itself in the terminal). I can curl that Url from within the container and get a response. I've also tried running the apprise cli from another container linked to this one and get the same error.

I can also retrieve the config from my local machine using an http request to the /get/ endpoint, but I cannot send notifications via the /notify/{key} endpoint. It just returns "One more more notification could not be sent."

I'm probably missing something obvious.

![image](https://user-images.githubusercontent.com/7397530/83521824-c1721c80-a4ad-11ea-9bd2-65624a9ced2e.png)

**Comment by caronc** [comment]
Hmm, everything looks as thought it should.  If you manually visit the website `http://localhost:8888/get/apprise` do you see your configuration?

I will try to reproduce this and get back to you.  It is possible that the CLI version of Apprise that you are using is an older version <0.8.4?

**Comment by bkonicek** [comment]
Visiting that url from my local machine returns an HTTP error. If I curl it from inside the container there's nothing returned, but I can see my config at `http://localhost:8888/cfg/apprise`.

I'm running apprise v.0.8.5 in all tests - both containers I'm testing with are the latest apprise-api images, and I also tried installing apprise CLI on my machine with pip, and had the same issue.

**Comment by bkonicek** [comment]
I took another look at this and after double checking my commands I was able to send notifications from my local machine by curling the `http://localhost:8888/notify/apprise`.

It looks like the problem was I was using `tags` as a parameter instead of `tag`. The README and other docs do have the correct name, but the landing page of the API UI is incorrectly showing `tags`.  I'm a little unclear if the `tag` property is required for curl or not though. If I remove it altogether from my request body it fails, but if I include it with either `all`, a single tag name, or a comma separated list it works fine.

However, I'm still having the same problem as before with the apprise cli commands.

**Comment by caronc** [comment]
Thank you for doing all this research and reporting back; you're awesome. :trophy:! Seriously, I know it's frustrating when you post stuff and the developer never gets back to you for an answer (in this case... me) and you end up doing the research yourself. :wink: . I've been in your shoes too.  I sadly have a number of open tickets I've been neglecting just because life has gotten really busy over here.

I do intend to hopefully look at this tomorrow or sometime this weekend. I saw that you cloned the repository; so I'll also gladly entertain a merge request from you if you beat me to it!

It looks like i should update the documentation to reflect the problem then as well.

**Comment by bkonicek** [comment]
No worries at all! I appreciate you taking a look, but no pressure at all to get back to me quickly, everyone has a lot going on right now.

I did clone the repository but I haven't actually taken a look at the API or apprise code at all to try and fix anything, I just fixed the `tag`/`tags` text in the welcome page, but happy to open a PR for that if you haven't already gotten to it.

**Comment by caronc** [comment]
You should be good to go! Please let me know if you still have any problems.  You will need to check out the master branch of apprise for this to work for you though. Unfortunately 0.8.5 did have a bug in it that you brought forth.
