### ISSUE TITLE
Add Prometheus Metrics

### ISSUE THREAD

**Issue by MarkCupitt** [caronc/apprise-api#155]
:bulb: **The Idea**
In an enterprise environment, we would like to be able to monitor messages using Prometheus Metrics

This wudl let us monitor activity, efficiency and performance and scale as necessary

https://prometheus.github.io/client_python/getting-started/three-step-demo/

:hammer: **Breaking Feature**
DOnt think it would break anything,

**Comment by caronc** [comment]
Duplicate of #143
