### ISSUE TITLE
Signal using curl: django.request: Failed Dependency: /notify/apprise

### ISSUE THREAD

**Issue by NetSamurai** [caronc/apprise-api#162]
:mega: **Notification Service(s) Impacted**
Signal

:lady_beetle: **Describe the bug**
Got `apprise-api` set up, with an internal reverse proxy and routing, and all appears fine. I use the `lsio` container, but they said I should report this upstream.

I only have one signal entry in the configuration, a group. `signal_group=signal://signal-cli-rest-api:8080/+555555555/group.xyzXiIEFWJFIWEJFIWEJFIWEJFIEJWijwfweijfwiejfwef=` which seems to work fine when I `docker exec -it apprise-api bash` then `apprise -vv -t "Test" -b "XYZ" --tag=all --config=http://localhost:8000/get/apprise`. That works.

But when I try to call it with `curl` that's when it stops working. 
```
curl --insecure -X POST \
    -F "body=Test Message" \
    -F "tags=all" \
    https://notify.some-dmz-server1.home/notify/apprise
```

:bulb: **Screenshots and Logs**
In the `docker logs apprise-api`, it shows the error in the title: 
```
[pid: 146|app: 0|req: 29/29] 172.28.0.105 () {52 vars in 843 bytes} [Tue Jan  9 08:11:21 2024] POST /notify/apprise => generated 72 bytes in 3 msecs (HTTP/1.1 424) 5 headers in 297 bytes (1 switches on core 0)
2024-01-09 08:12:54,535 [INFO] apprise: Loaded 1 entries from memory://
2024-01-09 08:12:54,536 [WARNING] django.request: Failed Dependency: /notify/apprise
```

:computer: **Your System Details:**
 - OS: Debian 12+
 - Container: https://docs.linuxserver.io/images/docker-apprise-api/

Thank you for any help you or suggestions you may provide!

**Comment by caronc** [comment]
So one thing i noticed is you're setting `tags=` try setting `tag=` instead.

I will leave this ticket open and add support for `tags=` as well for future releases.

**Comment by NetSamurai** [comment]
Ack, that was it. Thank you!

**Comment by caronc** [comment]
Closing ticket as last MR improves logging which should help resolve your concern

**Comment by YouveGotMeowxy** [comment]
I had the same problem. I copied the curl example from the Web UI, which has "tags" instead of "tag", and it gave me the error, and doesn't send anything.

![image](https://github.com/caronc/apprise-api/assets/39491297/135c53f3-eff9-4613-8a02-2591f4063d4e)
