### ISSUE TITLE
Errors in the CURL examples in configuration overview

### ISSUE THREAD

**Issue by odwulf** [caronc/apprise-api#165]
:beetle: **Describe the bug**
On the Config Management page, all CURL examples use a "**tags**" field. According to my tests, it should be the singular "**tag**", even when using multiple tags.

**Comment by caronc** [comment]
I just added `tag` in the last PR. `tags` will work too (because it was causing confusion) but you need to use the `:edge` branch for now not `:latest`

**Comment by caronc** [comment]
This has now been pushed into `:latest`; closing off ticket
