### ISSUE TITLE
Refactor General Display of Loaded URLs

### ISSUE THREAD

**Issue by YouveGotMeowxy** [caronc/apprise-api#174]
:question: **Question**

Not a problem or issue or anything, but looking at the WebUI, would it make more sense to place the "Loaded Configuration" section on the "overview" tab, to the bottom of the actual "Configuration" tab instead of where it's currently at?

And maybe even style it into more of a table instead of stacked and full width? Would save a lot of scrolling if a lot of configs/tags are added. :)

Something kinda like this:

```
-------------------
| config | config |
-------------------
| config | config |
-------------------
| config | config |
-------------------
| config | config |
-------------------
```

instead of how it is now:

```
---------
| config | 
---------
| config | 
---------
| config | 
---------
| config | 
---------
| config | 
---------
| config | 
---------
| config | 
---------
| config | 
----------
```

**Comment by STaRDoGG** [comment]
@caronc I can tweak a few things like I've been doing, but a whole reface I just don't have time for. I'm buried in projects, lol.

I'm really also not the greatest UI guy in the world, and don't really know the UI framework you used at all, and don't have a dev environment for it all setup. I'm just tweaking things via the browser dev inspector.

I really don't think the UI is that bad though for what it needs to do.

If you want to move that little bit of html over from the Overview tab ("Loaded Configuration
") to the Configuration tab, like mentioned above, I can add a PR for the styling in the screenshot.

**Comment by YouveGotMeowxy** [comment]
Any updates on this? :)

**Comment by STaRDoGG** [comment]
> Any updates on this? :)

*shrug* I'm waiting on @caronc

**Comment by caronc** [comment]
Go for it, i welcome any PR 🙂

**Comment by YouveGotMeowxy** [comment]
> Go for it, i welcome any PR 🙂

@caronc I think he's waiting on this first? :)

> If you want to move that little bit of html over from the Overview tab ("Loaded Configuration") to the Configuration tab, like mentioned above, I can add a PR for the styling in the screenshot.

**Comment by caronc** [comment]
I think i'm happy with the results; i'll merge the code after your review (see attached PR for screenshots).

**Comment by caronc** [comment]
Massive refactoring complete of css, extra tab as requested, and cleaned up some of the general look of both dark and light theme.

Closing off issue; right now content is available from `:edge` branch, but soon `:latest`
