### ISSUE TITLE
Trying to set up API in Photon

### ISSUE THREAD

**Issue by mattpackwood** [caronc/apprise-api#192]
:question: **Question**

I think I may have missed step, I am unable to save my YAML...

<img width="485" alt="Screenshot 2024-06-08 at 10 38 04 AM" src="https://github.com/caronc/apprise-api/assets/1097448/3b87ce5e-4e47-42a2-a257-3ad67ef58a81">

<img width="399" alt="Screenshot 2024-06-08 at 10 38 23 AM" src="https://github.com/caronc/apprise-api/assets/1097448/f113a4b9-38a7-4880-adc4-439a335baf48">

**Comment by caronc** [comment]
[See Here](https://github.com/caronc/apprise-api?tab=readme-ov-file#config-directory-permissions)

**Comment by mattpackwood** [comment]
When I go to:
<img width="396" alt="Screenshot 2024-06-12 at 6 44 48 PM" src="https://github.com/caronc/apprise-api/assets/1097448/62a50446-89db-412c-8bc3-0bab0673dba7">



I am getting:
<img width="399" alt="Screenshot 2024-06-12 at 6 44 34 PM" src="https://github.com/caronc/apprise-api/assets/1097448/adb2e895-ebd4-4661-a4e1-b56c7e203b68">


It is very possible the issue is that I am running the container under Photon OS.

I have a file:
```
# Grant full permission to the local directory you're saving your
# Apprise configuration to:
chmod 777 /var/lib/apprise/config
```

Stored under:
```
root@photon-machine [ /var/lib/apprise/config ]# pwd
/var/lib/apprise/config
root@photon-machine [ /var/lib/apprise/config ]# ls
apprise_config
root@photon-machine [ /var/lib/apprise/config ]# 
```

**Comment by caronc** [comment]
Are you sure it's not writing to `/config` if you're using my docker container?  You're having a similar problem to #195.  Perhaps there is something else going on in the source code. I may have to have a deeper look this weekend

**Comment by caronc** [comment]
Have a look at the latest source code.  I greatly improved the permission element of the API by introducting `PUID` and `PGID` variables where you can set the permission the tool should run as.

**Comment by caronc** [comment]
The new update i just pushed supports the `PUID` and `PGID` environment variables. Hopefully they help you out.

**Comment by mattpackwood** [comment]
Good news is that a:
`sudo chmod --recursive 777 attach/ config/ plugin/`
Fixed the permission issue, now I need to tighten up the security a bit, my config file is currently:
```
# Grant full permission to the local directory you're saving your
# Apprise configuration to:
chmod 777 /var/lib/apprise/config
```
I can't find the page that shows the "more secure version of this" I can't seem to find that, I am sure it was in this repository....

**Comment by mattpackwood** [comment]
Bizarrely I can find this in the Spanish but not the English "Read Me".  [https://github.com/caronc/apprise-api/blob/e3352206f3b53f5ffc722310619b9cfe520b2c7e/README-es.md?plain=1#L86](https://github.com/caronc/apprise-api/blob/e3352206f3b53f5ffc722310619b9cfe520b2c7e/README-es.md?plain=1#L86)

**Comment by caronc** [comment]
Link: https://github.com/caronc/apprise-api/blob/e3352206f3b53f5ffc722310619b9cfe520b2c7e/README.md

**Comment by mattpackwood** [comment]
Got it, time to experiment!
