### ISSUE TITLE
Issues with Name of S3 Signed URL Attachment

### ISSUE THREAD

**Issue by dnimon** [caronc/apprise-api#204]
:mega: **Notification Service(s) Impacted**
SMTP

:lady_beetle: **Describe the bug**
Hello! I'm using apprise api (great project by the way)

I'm running into an issue with adding attachments that are signed s3 urls. I was able to successfully send an attachment with the smtp mode but the name was "attachment.001" instead of the file name. It looks like when sending the url you can add a query parameter of a "name" from what I can see in the code. That does not work and gives that error. Without that, I get that strange name instead of the s3 file name.

:bulb: **Screenshots and Logs**

If I try that though I get the following error:

apprise-1  | 2024-08-01 16:34:35,041 [WARNING] django: NOTIFY - 127.0.0.1 - Bad attachment: apprise.attachment.http.AttachHTTP.__init__() got multiple values for keyword argument 'name'

:computer: **Your System Details:**
 - OS: Running through docker and apprise-api
 - Python Version: Same as docker container for apprise-api

:crystal_ball: **Additional context**

**Comment by caronc** [comment]
Closing having not heard back
