### ISSUE TITLE
Cryptography dependency won't compile in Docker Container

### ISSUE THREAD

**Issue by caronc** [caronc/apprise-api#217]
:beetle: **Describe the bug**

@stumpylog, I'm wondering if you'd be able to help me with this since you are a docker expert thanks to an great multistage PR you made against this project a while back ([here](https://github.com/caronc/apprise-api/pull/150)).

The problem is that cryptgography hangs for 6+ hrs in the multistage now and eventually GitHub Actions just kills it off.  I retried 3 times to biuld it without any luck.

I can't spot anything obvious, so i'm just opening a ticket for others who could possibly notice or lend a hand?

Failed Job (attempt no 3 link: https://github.com/caronc/apprise-api/actions/runs/12423893680/job/34746045843
![image](https://github.com/user-attachments/assets/a7cc8e4c-8b86-429e-beaa-cf0888ba451b)

**Comment by stumpylog** [comment]
I don't have a ton of time right now, but is there a reason cryptography is built from source instead of installing via a wheel?

**Comment by caronc** [comment]
I do recall a reason to resorting to compiling, I can't recall. There were a lot of limitations with the wheel at the time

**Comment by stumpylog** [comment]
Based on some history, it appears to have been for armv7, but that's not built.  I would transition to the wheel and save a bunch of time

**Comment by stumpylog** [comment]
Seems like it worked fine recently: https://github.com/caronc/apprise-api/actions/runs/12447548167

If you still want to build from source, perhaps it was a bug in some version of the building.  I see the same version of buildx, and generally other tools.

But I don't see a reason to build from source. If you would like, I can remove the building and just install from the wheel.

Also, separately, if you're open to it, I could do some modernizing of the packaging here, into a pyproject.toml format, etc

**Comment by caronc** [comment]
Thank you so much for the offer. I've been dealing with a family crisis for the past month and have not got to work or investigate much on this project. Anything you could offer would be so much appreciated 🙏 

Happy holidays as well! ⭐

**Comment by caronc** [comment]
@stumpylog : You're amazing; thank you so much! :heart: :rocket: :pray: 

[It appears to have worked wonderfully!](https://github.com/caronc/apprise-api/actions/runs/12521557588/job/34928774749); the version has been re-aligned with the merge of this branch to the master.
