### ISSUE TITLE
Error 500 - Cannot save configuration when using docker

### ISSUE THREAD

**Issue by maudrid** [caronc/apprise-api#30]
:question: **Question**
I've deployed  the docker container to my local host.
I checked that the config volume mapping is in place and working as recommended in the documentation.
When I access the web interface and place either text or yaml settings and try to save, the POST request to the server returns with internal server 500.
From the docker log, I can only see the request being logged with 500 response code, no other error messages.
I have also tried running the docker container without the volume mapping, but have the same result.

**Comment by caronc** [comment]
Sorry for the late reply,  I've seen this issue come up a few times.  It's to do with the permissions to your mounted /config directory from within your container.  They aren't write permissions by your web user your docker container is running as to the external mount you set up.

**Comment by maudrid** [comment]
Thanks I got is working now.
It turns out that on the Docker Host, the user that was trying to access the config volume was `www-data`.
Giving that user access, fixed the problem.
