### ISSUE TITLE
Error occurred sending MSTeams notification

### ISSUE THREAD

**Issue by rafaela2** [caronc/apprise-api#38]
:beetle: **Describe the bug**
Lately, I can't send messages by Teams with Apprise container on windows machine. I had tried more than one windows machine and the same error occurred. When I try on docker with linux machine it's work.

:bulb: **Screenshots and Logs**
2021-02-02 11:16:41,055 [WARNING] apprise: A Connection error occurred sending MSTeams notification.
2021-02-02 11:16:41,060 [WARNING] django.request: Failed Dependency: /notify/mykey

:computer: **Your System Details:**
 - Docker Desktop for Windows (3.0.0) - WSL 2.
 
:crystal_ball: **Additional context**
On linux the same error message is shown but the message is sent normally.
I already sent messages for Teams with Apprise container on Docker Desktop For Windows normally before.

Even inside the container the error occurred:
apprise -vv -t "Test Message Title" -b "Test Message Body" msteams://13d3ff3e-..

**Comment by caronc** [comment]
This is really weird:
* `django.request: Failed Dependency: /notify/mykey`

I'll see what I can figure out.  Did it ever work for you before in Windows?

**Comment by rafaela2** [comment]
Yes, it did. The last time I tried in Windows and it worked, which I remember was on October 2020.

**Comment by caronc** [comment]
@rafaela2 : By chance would you be able to look at the branch i created (it's not part of the Apprise API though)?

I'd be curious if your issue relates to a recent Microsoft Teams Webhook change where the actual webhook is slightly different then before... follow pull request above for details.

**Comment by caronc** [comment]
I pushed a new update of Apprise today. With that, I also updated the Apprise-api to reference it. Try pulling down the latest version and let me know if it helped your problem at all.

**Comment by caronc** [comment]
Is this issue still occurring for you?

**Comment by caronc** [comment]
closing issue as no response in a while
