### ISSUE TITLE
Telgram on apprise-api webui

### ISSUE THREAD

**Issue by mariomare22** [caronc/apprise-api#43]
:question: **Question**
I am trying to follow this
https://github.com/caronc/apprise-api
to setup a notification with telegram but I get the following error.

my construct is:

mytag = tgram://BOT:bot/chatid

what am I doing wrong?

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/12135860/108993954-7e8b5100-769b-11eb-884c-c07c8e9c5086.png">

**Comment by mariomare22** [comment]
From the container this works fine `apprise -vv -t "Test Message Title" -b "Test Message Body"    tgram://BOT:bot/-chatid`

**Comment by mariomare22** [comment]
Issue is resolved but i guess i found a bug (maybe).
It could not write on the folder i mounted because user www-data inside the container did not have write permission.
can this be changed to the user which runs the container? 
right now i need 777 permission on the apprise folder.

**Comment by caronc** [comment]
See #31.  I'm not keen on the `777` permission solution, but i'll document this better and keep you posted! :slightly_smiling_face:
