### ISSUE TITLE
Ability to disable all but notify in persistent storage use case

### ISSUE THREAD

**Issue by skimpax** [caronc/apprise-api#46]
:bulb: **The Idea**
Once my whole configuration has been setup (persistent mode), I would like to be able to run apprise-api on that configuration, but disabling any further configuration modification (a kind of 'READ-ONLY mode' or 'admin mode').
My goal is to avoid that someone alterates that configuration.

Here would be targeted use case:
1. Launching the apprise-api inside a docker container (in 'persistent RW mode', iow. as it works currently). This mode is to be used in rare cases.
2. Setup my whole persistent configuration via de Configuration Manager.
3. Stop that container en re-run it in 'RO mode' (the feature I would appreciate). In everyday life, apprise would be in RO mode.
4. Other users can now use the container pour notification purpose only.

In that later mode, only notify is allowed to clients, maybe some GET commands, as long as they do not modify the configuration and do not expose sensible info (eg. account/password))

Maybe the naming could also be 'open mode' vs 'notify mode'... or whatever...

Thanks for apprise tool!

**Comment by skimpax** [comment]
I would like to avoid to involve a new third party like nginx to add the feature, so I would rank this proposal as last for my own case.
The second proposal seems less explicit than first, less understandable for apprise users.
So my preference is the for the first solution, which looks more immediate as an apprise user.
That's just my own poll!
Thanks.

**Comment by caronc** [comment]
I think you'll be happy with the last merge request.  It addresses your concerns (for now it's just in the `master` branch.  I'll need to work out the issue taking place (completely different subject) with `cryptography` which is preventing the docker container from building anymore.

I'm very sorry for taking so long to get to your issue.
