### ISSUE TITLE
is there a way to get the valid keys?

### ISSUE THREAD

**Issue by dpeart** [caronc/apprise-api#47]
I set this up about a year ago and it has been working perfectly.  I then changed my cell service and need to update my information so I can get text message notifications again.

I can't remember my key.  I have a /config that I mount to have a persistent setup.

Is there a way to get apprise to respond with the valid keys?

thanks
david

**Comment by caronc** [comment]
Sorry to take so long to get back to you.  There is no way to get the valid keys no; not when you're set to `hash` (which is the default).  For the future, you can turn this off so the keys are written just as they're titled in the website. Just set the `APPRISE_STATEFUL_MODE` to `simple` .  Keep in mind though if you switch, your existing configuration may get lost; be sure to back it up first (as file hashing is done differently)
