### ISSUE TITLE
Follow up to pull request #26 to use the BASE_URL environment variable everywhere it should.

### ISSUE THREAD

**Issue by gjdoornink** [caronc/apprise-api#50]
Hello,

In pull request #26 the BASE_URL environment variable was added.
It seems that the BASE_URL environment variable was not used everywhere it should have been.
I have submitted pull request #48 to fix this.
Besides that, this pull request also fixes two incorrect href url parts ('welcome' and 'config').

Kind regards,

**Comment by caronc** [comment]
Thank you so much. I forgot all about your pull request!

I'm out of town (replying on my phone). When I get access to Internet I'll quickly review and merge.

Again, sorry that you waited so long and thank you for opening this ticket as a reminder! 🙂

**Comment by gjdoornink** [comment]
No problem, thanks for your reply :-)
