### ISSUE TITLE
Permissions inside container for /var/log/supervisor

### ISSUE THREAD

**Issue by Nascentes** [caronc/apprise-api#72]
:beetle: **Describe the bug**

caronc/apprise:latest          "/usr/bin/supervisord"   18 minutes ago   Restarting (1) 14 seconds ago  

I'm not sure if this could be qualified as a bug over a misconfig on my side with the latest image, but since updating my container has been stuck in a restart loop. Logs presenting a single stacktrace over and over as:

`PermissionError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log'`

This directory is not a mounted volume (unless there's some in-container shenanigans that map it to /var/lib/apprise/config? 

:bulb: **Screenshots and Logs**

```
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 359, in main
    go(options)
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 369, in go
    d.main()
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 72, in main
    self.options.make_logger()
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1494, in make_logger
    loggers.handle_file(
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 419, in handle_file
    handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 213, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 160, in __init__
    self.stream = open(filename, mode)
PermissionError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log' 
```

Here is my current ENV that was working OK:
```
            "Env": [
                "LOG_LEVEL=DEBUG",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.8.7",
                "PYTHON_PIP_VERSION=20.3.3",
                "PYTHON_SETUPTOOLS_VERSION=57.5.0",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py",
                "PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2",
                "PYTHONDONTWRITEBYTECODE=1",
                "PYTHONUNBUFFERED=1",
                "APPRISE_CONFIG_DIR=/config",
                "CRYPTOGRAPHY_DONT_BUILD_RUST=1",
                "PUID=1042",
                "GID=100",
                "UID=1042"
            ],
            "Cmd": [
                "/usr/bin/supervisord"
            ],
            "Image": "caronc/apprise:latest",

```

:computer: **Your System Details:**
4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:35 CST 2021 x86_64 GNU/Linux synology_apollolake_1019+
DSM version: DSM 6.2.4-25556

:crystal_ball: **Additional context**
Just to be thorough, I did the following:
- Pull latest image
- Reset docker container (previously "Clear" in Synology docker GUI)
- Start container with new image

no added details setting LOG_LEVEL=DEBUG

**Comment by Nascentes** [comment]
I was able to manually spin up a new container via:

```
docker run -dit --name apprise -p 8124:8000 -v /volume1/docker/apprise:/config:rw -e PUID=1042
 -e UID=1042 -e GID=100 caronc/apprise:latest
```

Seems to be OK again. Not sure why persistent config isn't being written though. I just realized that the directory is completely empty. Do I _need_ to create a user with UID=33 & use that for permissions...? Any chance of making this overridable? (of the 20-some-odd containers I run, this is the only one that doesn't allow this so far, unless I'm just missing something...)

**Comment by caronc** [comment]
Sorry for not getting back to you.

If you're okay to close it i will.  But please let me know if this persists again or if you think it's a bug.

**Comment by eresonance** [comment]
I had the same issue, although I was using docker-compose with a few other associated containers. Restarting the whole lot fixed the issue; I was already using a docker volume for persistent storage though.

**Comment by caronc** [comment]
Closing this issue off
