### ISSUE TITLE
unable to save configuration

### ISSUE THREAD

**Issue by elax46** [caronc/apprise-api#75]
:question: **Question**
I'm trying to set up tweeting
`apprise -b "$TWEETTEXT" twitter://$TWITTER_CONSKEY/$TWITTER_CONSSECRET/$TWITTER_ACCTOKEN/$TWITTER_ACCSECRET/?mode=tweet`
![Immagine 2022-05-25 105020](https://user-images.githubusercontent.com/55278049/170222451-5e1c5ad2-1421-4142-b378-3746fb13c10a.png)

use is for Uptime Kuma

**Comment by caronc** [comment]
I think you just need to fix your permissions where you mounted the configuration directory

**Comment by elax46** [comment]
Hi thank you for your answer no in the end I was able to trace the problem for the publication of automatic tweets twitter asks for the API v2 of high level with essential access no, I suggest you update the wiki underlining this aspect

**Comment by caronc** [comment]
@elax46 can you just elaborate a bit on what you did here? I think this ties back to a question someone is having here: https://github.com/caronc/apprise/issues/552

Was it that you had to use v2, or that you did not?
