### ISSUE TITLE
Apprise Theme: Nord

### ISSUE THREAD

**Issue by STaRDoGG** [caronc/apprise-api#79]
I tend to like dark themes, especially a [Nord](https://www.nordtheme.com/) dark theme, so took some time out to create one for Apprise.

If anyone's interested it can be grabbed here: https://github.com/STaRDoGG/apprise-nord-dark-theme

Screenshots at the link above as well.

**Comment by caronc** [comment]
That looks fantastic. I can update the main readme if you want. Alternatively, if you want to make a pull request to try integrating as light/dark theme that saves to a cookie (so it remembers when you come back) feel free.

Thoughts?

**Comment by STaRDoGG** [comment]
Sure, updating the main readme would be great. 👍🏼

Also, I'm all for including the choice to select themes from the config section (including cookie), but i don't have the time to get involved in all that. If you want to though, feel free to include the theme. I'd just as some kind of "nod" somewhere just for the time spent making it. 🙂

I also just noticed a small "oops" in the theme that i missed. I'll be updating it later tonight when i get the chance probably.

**Comment by caronc** [comment]
Code merged (accessible via `:edge` at this time!  :rocket: - Closing ticket
