### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by pikeas** [caronc/apprise-api#85]
:lady_beetle: **Describe the bug**
Official Docker container uses ~600+ MB of RAM baseline, no notifications or config.

:bulb: **Screenshots and Logs**
```
$ docker stats <container_id>
CONTAINER ID    NAME            CPU %   MEM USAGE / LIMIT   MEM %   NET I/O     BLOCK I/O     PIDS
<id>            apprise-<id>    0.05%   589.1MiB / 600MiB   98.19%  0B / 0B     0B / 8.19kB    28
```

**Comment by caronc** [comment]
I believe i fixed this in the last merge request [here](https://github.com/caronc/apprise-api/commit/d7824e24c71117cf1df11a25a8c6cd637ec14c8f).

You should be able to use `APPRISE_WORKER_COUNT` variable and set it to `2` to accomplish what you want.

**Comment by caronc** [comment]
Closing off this issue as it has been open for some time now
