### ISSUE TITLE
how can update docker to latest?

### ISSUE THREAD

**Issue by johnfelipe** [caronc/apprise-api#88]
how can update docker to latest?

**Comment by caronc** [comment]
I'll be doing a new build soon. I'm just traveling abroad. I should be back in a week.

If you can't wait, just download the current dockerfile in this repo and add a pip install line like this before you deploy the container:

```bash
pip install git+https://github.com/caronc/apprise
```

**Comment by johnfelipe** [comment]
ping me when is ready new build, ill wait better

**Comment by caronc** [comment]
You could just copy line 22. Make a new entry below (line 23) and put:

```Dockerfile
RUN pip3 install --upgrade git+https://github.com/caronc/apprise
```

**Comment by johnfelipe** [comment]
this way

https://gist.github.com/ff7e2dd8c8f0c14e421f44d849eaa87c

and next?

**Comment by caronc** [comment]
I think this should work provided you run the command in the directory you placed the Dockerfile.

```bash
docker run --name apprise \
   -p 8000:8000 \
   -v /var/lib/apprise/config:/config \
   .
```

**Comment by johnfelipe** [comment]
`e7a82d097c1e   caronc/apprise:latest                     "/usr/bin/supervisor…"   4 weeks ago   Exited (255) 4 weeks ago    0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                       apprisepermanente`
next
```
root@felipe:~/apprise-api# docker run --name apprisepermanente2 \
>    -p 8000:8000 \
>    -v /var/lib/apprise/config:/config \
>    .
```

show this error

```
docker: invalid reference format.
See 'docker run --help'.

```

**Comment by johnfelipe** [comment]
can u share pls full file for update apprise for latest apprise release 20 min ago?

**Comment by caronc** [comment]
It's built on dockerhub now.  You just need to rebuild your container (same way you did it before opening this ticket originally).

The latest source code can be found there.

**Comment by caronc** [comment]
Closing this ticket off due to lack of response; latest version can be found on DockerHub and GitHuB
