### ISSUE TITLE
Json payload to add attachments to a Discord notification

### ISSUE THREAD

**Issue by namelivia** [caronc/apprise-api#98]
:question: **Question**
Hello! I'm trying to post a Discord notification but I have not been able to make the attachments show up, and after looking for a bit I was unable to find any information. Can I add like for example, an image url, or a youtube video url as attachments?

I'm trying the following POST request:

```
curl -X POST http://my-apprise-microservice:8000/notify/testing -H "Content-Type: application/json" -d '{"attach": ["https://my/image/1.png", "https://my/image/2.png", "https://my/image/3.png"], "body": "test"}'

2023-01-20 07:59:46,465 [INFO] apprise: Loaded 1 entries from memory://
2023-01-20 07:59:46,466 [INFO] apprise: Notifying 1 service(s) asynchronously.
2023-01-20 07:59:46,688 [INFO] apprise: Sent Discord notification.
```
The notification gets delivered but I can only see the body. The images are reachable at those urls.
I've checked the logs but there is nothing about an error or anything, am I doing something wrong?

**Comment by caronc** [comment]
Closing this issue off as now Apprise API supports attachments in it's latest version :)

**Comment by namelivia** [comment]
This is awesome! I can't wait to try it! Thank you @caronc
