### ISSUE TITLE
Add supported services endpoint

### ISSUE THREAD

**Issue by dokime7** [caronc/apprise-api#99]
:bulb: **The Idea**
It would be cool to have an endpoint that returns the list of all supported services with some info like `service_name`, `secure_protocol`, `setup_url` and maybe `templates` from plugins object.

Thanks for this amazing tool!

**Comment by caronc** [comment]
Makes sense, this is already built into the underlining [Developer API](https://github.com/caronc/apprise/wiki/Development_API#details-dynamic-view-into-available-notification-services-apprise-offers) and [CLI tool](https://github.com/caronc/apprise/wiki/CLI_Usage#heavy_check_mark-compatibility-and-notification-details).

 I agree that it should have probably been exposed via this Web API too.

**Comment by dokime7** [comment]
Yes like [Developer API](https://github.com/caronc/apprise/wiki/Development_API#details-dynamic-view-into-available-notification-services-apprise-offers) !

**Comment by caronc** [comment]
I'm pretty happy with my changes; let me know your thoughts and if I'm forgetting anything.

**Comment by dokime7** [comment]
Hi,

Wouah I just tested it, it's amazing!
Exactly what I need, many thanks!!
